package com.expstudio.facilitycore.game

import android.graphics.Canvas
import android.view.MotionEvent
import com.expstudio.facilitycore.audio.Sfx
import com.expstudio.facilitycore.core.Draw
import com.expstudio.facilitycore.core.MathX
import com.expstudio.facilitycore.core.Palette
import kotlin.math.sin

/**
 * Coolant routing. A grid of pipe segments, each rotated a quarter turn per tap;
 * the loop is fed when an unbroken run of pipe joins the inlet on the left to
 * the outlet on the right.
 *
 * The board is generated by carving a real path first and then scrambling every
 * rotation, so a solution is guaranteed to exist and the scramble can never
 * accidentally leave the board already solved.
 */
class FlowPuzzle(
    seed: Long,
    private val cols: Int = 5,
    private val rows: Int = 4,
    caption: String = "Route coolant from the inlet to the outlet"
) : Overlay("COOLANT ROUTING", caption) {

    /** Bit per edge, clockwise from north. */
    private val masks = IntArray(cols * rows)

    private var cellSize = 0f
    private var gridLeft = 0f
    private var gridTop = 0f

    /** Cells currently fed from the inlet, recomputed after every turn. */
    private val fed = BooleanArray(cols * rows)

    /** Animates each tile's turn rather than snapping it. */
    private val spin = FloatArray(cols * rows)

    private var solvedFlash = 0f

    override val dismissible = true

    init {
        val rng = Compose.Rng(seed xor 0x5DEECE66DL)
        carve(rng)
        fill(rng)
        scramble(rng)
        recomputeFeed()
    }

    private fun idx(cx: Int, cy: Int) = cy * cols + cx

    /** Walks a path from the inlet row to the outlet, only ever moving forward or sideways. */
    private fun carve(rng: Compose.Rng) {
        var cx = 0
        var cy = rows / 2
        masks[idx(cx, cy)] = masks[idx(cx, cy)] or W
        // Bounded so a run of unlucky vertical picks can never hang generation.
        var guard = cols * rows * 4
        while (cx < cols - 1 && guard-- > 0) {
            // Bias toward advancing, so the path always terminates.
            val goVertical = rng.chance(0.38f) && rows > 1
            if (goVertical) {
                val up = if (cy == 0) false else if (cy == rows - 1) true else rng.chance(0.5f)
                val ny = if (up) cy - 1 else cy + 1
                masks[idx(cx, cy)] = masks[idx(cx, cy)] or (if (up) N else S)
                masks[idx(cx, ny)] = masks[idx(cx, ny)] or (if (up) S else N)
                cy = ny
            } else {
                masks[idx(cx, cy)] = masks[idx(cx, cy)] or E
                masks[idx(cx + 1, cy)] = masks[idx(cx + 1, cy)] or W
                cx++
            }
        }
        masks[idx(cx, cy)] = masks[idx(cx, cy)] or E
        outletRow = cy
    }

    private var outletRow = 0

    /** Everything off the path gets a plausible piece, so the board reads as plumbing. */
    private fun fill(rng: Compose.Rng) {
        var i = 0
        while (i < masks.size) {
            if (masks[i] == 0) {
                masks[i] = when (rng.int(4)) {
                    0 -> N or S
                    1 -> E or W
                    2 -> N or E
                    else -> S or W
                }
            }
            i++
        }
    }

    private fun rotate(m: Int): Int = ((m shl 1) or (m ushr 3)) and 0xF

    private fun scramble(rng: Compose.Rng) {
        var i = 0
        while (i < masks.size) {
            var turns = rng.int(4)
            // A straight pipe is the same shape after two turns, so a "random"
            // turn count would leave half the board untouched.
            if (masks[i] == (N or S) || masks[i] == (E or W)) turns %= 2
            var t = 0
            while (t < turns) { masks[i] = rotate(masks[i]); t++ }
            i++
        }
        if (isSolved()) {
            // Vanishingly unlikely, but a puzzle that opens solved is a bug the
            // player would read as the game skipping itself.
            masks[0] = rotate(masks[0])
        }
    }

    /** Flood fill from the inlet through matching openings. */
    private fun recomputeFeed() {
        java.util.Arrays.fill(fed, false)
        val start = idx(0, rows / 2)
        if (masks[start] and W == 0) return
        val stack = ArrayDeque<Int>()
        stack.addLast(start)
        fed[start] = true
        while (stack.isNotEmpty()) {
            val cur = stack.removeLast()
            val cx = cur % cols
            val cy = cur / cols
            val m = masks[cur]
            if (m and N != 0 && cy > 0) tryFeed(cx, cy - 1, S, stack)
            if (m and S != 0 && cy < rows - 1) tryFeed(cx, cy + 1, N, stack)
            if (m and W != 0 && cx > 0) tryFeed(cx - 1, cy, E, stack)
            if (m and E != 0 && cx < cols - 1) tryFeed(cx + 1, cy, W, stack)
        }
    }

    private fun tryFeed(cx: Int, cy: Int, needed: Int, stack: ArrayDeque<Int>) {
        val i = idx(cx, cy)
        if (fed[i]) return
        if (masks[i] and needed == 0) return
        fed[i] = true
        stack.addLast(i)
    }

    private fun isSolved(): Boolean {
        recomputeFeed()
        val out = idx(cols - 1, outletRow)
        return fed[out] && masks[out] and E != 0
    }

    override fun onLayout() {
        val availW = panelW() * 0.82f
        val availH = panelH() * 0.62f
        cellSize = MathX.min(availW / cols, availH / rows)
        gridLeft = (panelLeft() + panelRight()) * 0.5f - cellSize * cols * 0.5f
        gridTop = panelTop() + panelH() * 0.28f
    }

    override fun onUpdate(dt: Float) {
        var i = 0
        while (i < spin.size) {
            if (spin[i] > 0f) spin[i] = (spin[i] - dt * 6f).coerceAtLeast(0f)
            i++
        }
        if (solvedFlash > 0f) {
            solvedFlash -= dt
            if (solvedFlash <= 0f) close(true)
        }
    }

    override fun onTouchEvent(e: MotionEvent) {
        if (e.actionMasked != MotionEvent.ACTION_DOWN || solvedFlash > 0f) return
        val cx = ((e.x - gridLeft) / cellSize).toInt()
        val cy = ((e.y - gridTop) / cellSize).toInt()
        if (cx !in 0 until cols || cy !in 0 until rows) return
        val i = idx(cx, cy)
        masks[i] = rotate(masks[i])
        spin[i] = 1f
        sfx?.invoke(Sfx.Id.CLICK)
        recomputeFeed()
        if (isSolved()) {
            sfx?.invoke(Sfx.Id.POWER)
            solvedFlash = 0.55f
        }
    }

    override fun onDraw(c: Canvas, d: Draw) {
        val gw = cellSize * cols
        val gh = cellSize * rows
        d.round(c, gridLeft - cellSize * 0.2f, gridTop - cellSize * 0.2f,
            gridLeft + gw + cellSize * 0.2f, gridTop + gh + cellSize * 0.2f,
            cellSize * 0.12f, Palette.withAlpha(Palette.VOID, 0.55f))

        // Inlet and outlet stubs, so the goal needs no explanation.
        val inY = gridTop + cellSize * (rows / 2 + 0.5f)
        val outY = gridTop + cellSize * (outletRow + 0.5f)
        d.rect(c, gridLeft - cellSize * 0.55f, inY - cellSize * 0.09f, gridLeft, inY + cellSize * 0.09f, Palette.ACCENT)
        val outLive = isSolved()
        d.rect(c, gridLeft + gw, outY - cellSize * 0.09f, gridLeft + gw + cellSize * 0.55f, outY + cellSize * 0.09f,
            if (outLive) Palette.GOOD else Palette.TEXT_DIM)
        d.glow(c, gridLeft + gw + cellSize * 0.55f, outY, cellSize * 0.5f,
            if (outLive) Palette.GOOD else Palette.BAD, if (outLive) 1f else 0.4f)

        var cy = 0
        while (cy < rows) {
            var cx = 0
            while (cx < cols) {
                drawCell(c, d, cx, cy)
                cx++
            }
            cy++
        }
    }

    private fun drawCell(c: Canvas, d: Draw, cx: Int, cy: Int) {
        val i = idx(cx, cy)
        val l = gridLeft + cx * cellSize
        val t = gridTop + cy * cellSize
        val mx = l + cellSize * 0.5f
        val my = t + cellSize * 0.5f
        d.round(c, l + 2f, t + 2f, l + cellSize - 2f, t + cellSize - 2f, cellSize * 0.10f,
            Palette.withAlpha(Palette.PANEL_EDGE, 0.55f))

        val live = fed[i]
        val tint = if (live) Palette.ACCENT else Palette.TEXT_DIM
        val thick = cellSize * (if (live) 0.17f else 0.13f)
        // A turning tile lifts slightly, which is the only feedback a tap gets.
        val lift = spin[i] * cellSize * 0.04f
        val m = masks[i]
        if (m and N != 0) d.rect(c, mx - thick, t + lift, mx + thick, my + thick, tint)
        if (m and S != 0) d.rect(c, mx - thick, my - thick, mx + thick, t + cellSize - lift, tint)
        if (m and W != 0) d.rect(c, l + lift, my - thick, mx + thick, my + thick, tint)
        if (m and E != 0) d.rect(c, mx - thick, my - thick, l + cellSize - lift, my + thick, tint)
        d.circle(c, mx, my, thick * 1.25f, tint)
        if (live) {
            val pulse = 0.5f + 0.5f * sin(time * 6f - cx * 0.6f - cy * 0.4f)
            d.glow(c, mx, my, cellSize * 0.42f, Palette.ACCENT, 0.35f * pulse)
        }
    }

    private companion object {
        const val N = 1
        const val E = 2
        const val S = 4
        const val W = 8
    }
}
