package com.expstudio.facilitycore.game

import android.graphics.Canvas
import android.view.MotionEvent
import com.expstudio.facilitycore.audio.Sfx
import com.expstudio.facilitycore.core.Draw
import com.expstudio.facilitycore.core.MathX
import com.expstudio.facilitycore.core.Palette
import kotlin.math.abs
import kotlin.math.hypot
import kotlin.math.sin
import kotlin.random.Random

/**
 * A full-screen modal minigame. Overlays own their own hit testing in screen
 * pixels; the session suspends world input while one is open.
 */
abstract class Overlay(val title: String, val hint: String) {
    var finished = false
        protected set
    var succeeded = false
        protected set
    /** Set when the player may back out without solving. */
    open val dismissible = true

    protected var w = 0f
    protected var h = 0f
    protected var time = 0f
    /** Rises 0 -> 1 on open, so every overlay shares one entrance animation. */
    protected var intro = 0f

    private var closeCx = 0f
    private var closeCy = 0f
    private var closeR = 0f

    var sfx: ((Sfx.Id) -> Unit)? = null

    fun layout(widthPx: Int, heightPx: Int) {
        w = widthPx.toFloat()
        h = heightPx.toFloat()
        closeR = h * 0.045f
        closeCx = panelRight() - closeR * 1.2f
        closeCy = panelTop() + closeR * 1.2f
        onLayout()
    }

    protected open fun onLayout() {}

    protected fun panelW(): Float = MathX.min(w * 0.82f, h * 1.62f)
    protected fun panelH(): Float = h * 0.80f
    protected fun panelLeft(): Float = (w - panelW()) * 0.5f
    protected fun panelTop(): Float = (h - panelH()) * 0.5f
    protected fun panelRight(): Float = panelLeft() + panelW()
    protected fun panelBottom(): Float = panelTop() + panelH()

    open fun update(dt: Float) {
        time += dt
        intro = MathX.moveToward(intro, 1f, dt * 3.2f)
        onUpdate(dt)
    }

    protected open fun onUpdate(dt: Float) {}

    fun close(success: Boolean) {
        succeeded = success
        finished = true
    }

    fun draw(c: Canvas, d: Draw) {
        val a = MathX.smoothStep(intro)
        d.rect(c, 0f, 0f, w, h, Palette.withAlpha(Palette.VOID, 0.78f * a))
        val grow = MathX.lerp(0.94f, 1f, a)
        val cx = (panelLeft() + panelRight()) * 0.5f
        val cy = (panelTop() + panelBottom()) * 0.5f
        val pw = panelW() * grow * 0.5f
        val ph = panelH() * grow * 0.5f
        d.panel(c, cx - pw, cy - ph, cx + pw, cy + ph, h * 0.03f)

        d.textCentered(c, title, cx, panelTop() + h * 0.075f, h * 0.052f, Palette.TEXT, true)
        d.textCentered(c, hint, cx, panelTop() + h * 0.135f, h * 0.034f, Palette.TEXT_DIM)

        onDraw(c, d)

        if (dismissible) {
            d.circleStroke(c, closeCx, closeCy, closeR, Palette.withAlpha(Palette.TEXT_DIM, 0.7f), 3f)
            val k = closeR * 0.42f
            d.line(c, closeCx - k, closeCy - k, closeCx + k, closeCy + k, Palette.TEXT_DIM, 3f)
            d.line(c, closeCx + k, closeCy - k, closeCx - k, closeCy + k, Palette.TEXT_DIM, 3f)
        }
    }

    protected abstract fun onDraw(c: Canvas, d: Draw)

    fun onTouch(e: MotionEvent): Boolean {
        if (e.actionMasked == MotionEvent.ACTION_DOWN) {
            val x = e.x
            val y = e.y
            if (dismissible && hypot(x - closeCx, y - closeCy) <= closeR * 1.4f) {
                sfx?.invoke(Sfx.Id.CLICK)
                close(false)
                return true
            }
        }
        onTouchEvent(e)
        return true
    }

    protected abstract fun onTouchEvent(e: MotionEvent)
}

/**
 * Intake breakers. Flipping a breaker also flips its neighbours; every breaker
 * must end up live. Generated by walking backwards from the solved state, so a
 * solution always exists.
 */
class BreakerPuzzle(seed: Long) : Overlay(
    "INTAKE BREAKER BANK",
    "Every breaker must read LIVE. Flipping one shakes its neighbours."
) {
    private val count = 5
    private val state = BooleanArray(count) { true }
    private val cellCx = FloatArray(count)
    private var cellCy = 0f
    private var cellW = 0f
    private var cellH = 0f
    private var solvedPulse = 0f
    private var wrongPulse = 0f
    private var resetL = 0f
    private var resetT = 0f
    private var resetR = 0f
    private var resetB = 0f
    private val initial: BooleanArray

    init {
        val rng = Random(seed)
        var attempts = 0
        do {
            state.fill(true)
            repeat(3 + rng.nextInt(3)) { toggle(rng.nextInt(count)) }
            attempts++
        } while (state.all { it } && attempts < 20)
        if (state.all { it }) { toggle(1) } // never hand the player a solved board
        initial = state.copyOf()
    }

    private fun toggle(i: Int) {
        state[i] = !state[i]
        if (i - 1 >= 0) state[i - 1] = !state[i - 1]
        if (i + 1 < count) state[i + 1] = !state[i + 1]
    }

    override fun onLayout() {
        val usable = panelW() * 0.82f
        cellW = usable / count * 0.72f
        cellH = panelH() * 0.34f
        cellCy = panelTop() + panelH() * 0.50f
        val startX = (w - usable) * 0.5f + usable / count * 0.5f
        for (i in 0 until count) cellCx[i] = startX + usable / count * i
        val bw = panelW() * 0.26f
        val bh = panelH() * 0.11f
        resetL = (w - bw) * 0.5f
        resetT = panelBottom() - bh * 1.65f
        resetR = resetL + bw
        resetB = resetT + bh
    }

    override fun onUpdate(dt: Float) {
        if (solvedPulse > 0f) {
            solvedPulse -= dt
            if (solvedPulse <= 0f) close(true)
        }
        if (wrongPulse > 0f) wrongPulse -= dt
    }

    override fun onDraw(c: Canvas, d: Draw) {
        for (i in 0 until count) {
            val l = cellCx[i] - cellW * 0.5f
            val r = cellCx[i] + cellW * 0.5f
            val t = cellCy - cellH * 0.5f
            val b = cellCy + cellH * 0.5f
            val on = state[i]
            val tint = if (on) Palette.GOOD else Palette.BAD
            d.round(c, l, t, r, b, cellW * 0.16f, Palette.withAlpha(tint, 0.10f))
            d.roundStroke(c, l, t, r, b, cellW * 0.16f, Palette.withAlpha(tint, 0.75f), 3f)

            // Physical lever: up when live, down when dead.
            val leverY = if (on) t + cellH * 0.26f else b - cellH * 0.26f
            d.line(c, cellCx[i], cellCy, cellCx[i], leverY, Palette.withAlpha(tint, 0.9f), cellW * 0.16f)
            d.circle(c, cellCx[i], leverY, cellW * 0.17f, tint)
            d.textCentered(c, if (on) "LIVE" else "DEAD", cellCx[i], b + cellH * 0.18f, cellH * 0.15f, tint, true)
            d.textCentered(c, "${i + 1}", cellCx[i], t - cellH * 0.16f, cellH * 0.15f, Palette.TEXT_DIM)
        }

        if (solvedPulse > 0f) {
            val a = (solvedPulse / 0.9f).coerceIn(0f, 1f)
            d.textCentered(c, "BANK LIVE", w * 0.5f, panelTop() + panelH() * 0.80f,
                h * 0.05f, Palette.withAlpha(Palette.GOOD, a), true)
        } else {
            d.round(c, resetL, resetT, resetR, resetB, (resetB - resetT) * 0.3f, Palette.withAlpha(Palette.TEXT_DIM, 0.12f))
            d.roundStroke(c, resetL, resetT, resetR, resetB, (resetB - resetT) * 0.3f, Palette.withAlpha(Palette.TEXT_DIM, 0.6f), 2f)
            d.textCentered(c, "RESET", (resetL + resetR) * 0.5f, (resetT + resetB) * 0.5f,
                (resetB - resetT) * 0.38f, Palette.TEXT_DIM, true)
        }
    }

    override fun onTouchEvent(e: MotionEvent) {
        if (e.actionMasked != MotionEvent.ACTION_DOWN) return
        if (solvedPulse > 0f) return
        val x = e.x
        val y = e.y
        if (x in resetL..resetR && y in resetT..resetB) {
            for (i in 0 until count) state[i] = initial[i]
            sfx?.invoke(Sfx.Id.CLICK)
            return
        }
        for (i in 0 until count) {
            if (abs(x - cellCx[i]) <= cellW * 0.65f && abs(y - cellCy) <= cellH * 0.75f) {
                toggle(i)
                sfx?.invoke(Sfx.Id.CONNECT)
                if (state.all { it }) {
                    solvedPulse = 0.9f
                    sfx?.invoke(Sfx.Id.CONFIRM)
                }
                return
            }
        }
    }
}

/**
 * The key pack's guts: four severed wires whose ends have been shuffled. Tap an
 * end on the left, then the matching colour on the right.
 */
class WiringPuzzle(seed: Long) : Overlay(
    "KEY PACK — INTERNAL LOOM",
    "Tap a torn end, then its matching colour on the other side."
) {
    private val pairs = 4
    private val rightOrder: IntArray
    private val joined = BooleanArray(pairs)
    private var selected = -1
    private var wrongFlash = 0f
    private var doneTimer = 0f

    private val leftY = FloatArray(pairs)
    private val rightY = FloatArray(pairs)
    private var leftX = 0f
    private var rightX = 0f
    private var nodeR = 0f

    override val dismissible = true

    init {
        val rng = Random(seed)
        val order = (0 until pairs).toMutableList()
        // Reshuffle until nothing is already in place: a straight-across wire
        // would look unbroken and read as a bug.
        var guard = 0
        do {
            order.shuffle(rng)
            guard++
        } while (guard < 40 && order.withIndex().any { (i, v) -> i == v })
        rightOrder = order.toIntArray()
    }

    override fun onLayout() {
        nodeR = panelH() * 0.055f
        leftX = panelLeft() + panelW() * 0.20f
        rightX = panelRight() - panelW() * 0.20f
        val top = panelTop() + panelH() * 0.30f
        val step = panelH() * 0.135f
        for (i in 0 until pairs) {
            leftY[i] = top + step * i
            rightY[i] = top + step * i
        }
    }

    override fun onUpdate(dt: Float) {
        if (wrongFlash > 0f) wrongFlash -= dt
        if (doneTimer > 0f) {
            doneTimer -= dt
            if (doneTimer <= 0f) close(true)
        }
    }

    override fun onDraw(c: Canvas, d: Draw) {
        // Housing.
        d.roundStroke(
            c, leftX - nodeR * 2.2f, panelTop() + panelH() * 0.24f,
            rightX + nodeR * 2.2f, panelTop() + panelH() * 0.24f + panelH() * 0.135f * (pairs - 1) + nodeR * 2.4f,
            nodeR * 0.7f, Palette.withAlpha(Palette.PANEL_EDGE, 0.9f), 2f
        )

        for (i in 0 until pairs) {
            val color = Palette.WIRE[i % Palette.WIRE.size]
            val rightIndex = rightOrder.indexOf(i)
            if (joined[i]) {
                d.line(c, leftX, leftY[i], rightX, rightY[rightIndex], Palette.withAlpha(color, 0.95f), nodeR * 0.42f)
                val midX = (leftX + rightX) * 0.5f
                val midY = (leftY[i] + rightY[rightIndex]) * 0.5f
                d.glow(c, midX, midY, nodeR * 1.1f, color, 0.7f)
            } else {
                // Torn stubs with a visible gap in the middle.
                d.line(c, leftX, leftY[i], leftX + panelW() * 0.10f, leftY[i], Palette.withAlpha(color, 0.8f), nodeR * 0.36f)
                d.line(c, rightX - panelW() * 0.10f, rightY[rightIndex], rightX, rightY[rightIndex],
                    Palette.withAlpha(color, 0.8f), nodeR * 0.36f)
            }
        }

        for (i in 0 until pairs) {
            val color = Palette.WIRE[i % Palette.WIRE.size]
            val pulse = if (selected == i) 0.5f + 0.5f * sin(time * 12f) else 0f
            drawNode(d, c, leftX, leftY[i], color, joined[i], pulse)
        }
        for (slot in 0 until pairs) {
            val wire = rightOrder[slot]
            val color = Palette.WIRE[wire % Palette.WIRE.size]
            drawNode(d, c, rightX, rightY[slot], color, joined[wire], 0f)
        }

        val remaining = joined.count { !it }
        val msg = when {
            doneTimer > 0f -> "PACK ONLINE"
            wrongFlash > 0f -> "WRONG PAIR"
            else -> "$remaining ${if (remaining == 1) "WIRE" else "WIRES"} LEFT"
        }
        val col = when {
            doneTimer > 0f -> Palette.GOOD
            wrongFlash > 0f -> Palette.BAD
            else -> Palette.TEXT_DIM
        }
        d.textCentered(c, msg, w * 0.5f, panelBottom() - panelH() * 0.10f, h * 0.042f, col, true)
    }

    private fun drawNode(d: Draw, c: Canvas, cx: Float, cy: Float, color: Int, done: Boolean, pulse: Float) {
        d.circle(c, cx, cy, nodeR * (1f + pulse * 0.15f), Palette.withAlpha(color, if (done) 0.85f else 0.25f))
        d.circleStroke(c, cx, cy, nodeR, Palette.withAlpha(color, 0.95f), 3f)
        if (done) d.circle(c, cx, cy, nodeR * 0.35f, Palette.TEXT)
    }

    override fun onTouchEvent(e: MotionEvent) {
        if (e.actionMasked != MotionEvent.ACTION_DOWN || doneTimer > 0f) return
        val x = e.x
        val y = e.y
        for (i in 0 until pairs) {
            if (!joined[i] && hypot(x - leftX, y - leftY[i]) <= nodeR * 1.6f) {
                selected = i
                sfx?.invoke(Sfx.Id.CLICK)
                return
            }
        }
        if (selected < 0) return
        for (slot in 0 until pairs) {
            if (hypot(x - rightX, y - rightY[slot]) <= nodeR * 1.6f) {
                val wire = rightOrder[slot]
                if (joined[wire]) return
                if (wire == selected) {
                    joined[wire] = true
                    selected = -1
                    sfx?.invoke(Sfx.Id.CONNECT)
                    if (joined.all { it }) {
                        doneTimer = 1.0f
                        sfx?.invoke(Sfx.Id.CONFIRM)
                    }
                } else {
                    wrongFlash = 0.45f
                    selected = -1
                    sfx?.invoke(Sfx.Id.DENY)
                }
                return
            }
        }
    }
}
